import React, { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { Marked } from 'marked';
import { GoogleGenAI } from '@google/genai';
import { VaultItem, UserProfile, Message } from '../types';
import { backend } from '../services/backend';
import SmeProBuilderModal from './SmeProBuilderModal';
import SaveToVaultModal from './SaveToVaultModal';

interface VaultProps {
  userProfile: UserProfile;
  onClose: () => void;
  onManageCategories: () => void;
}

type SortByType = 'timestamp' | 'context' | 'category';
type ExtendedVaultItem = VaultItem & { key: string };

const BuilderIcon: React.FC = () => (
    // FIX: Replaced the `title` prop with a <title> element inside the SVG for proper accessibility and to fix the type error.
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-4 h-4 text-cyan-400 flex-shrink-0">
        <title>Generated by SMEPro Builder</title>
        <path d="M11.354 1.646a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.354.146H2.5a.5.5 0 0 1-.5-.5v-1.146a.5.5 0 0 1 .146-.354l10-10Z" />
        <path d="M10.5 2.5a.5.5 0 0 0-.5-.5H3a.5.5 0 0 0-.5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5V7h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h1.146l-2-2Z" />
    </svg>
);


const Vault: React.FC<VaultProps> = ({ userProfile, onClose, onManageCategories }) => {
    const [allItems, setAllItems] = useState<ExtendedVaultItem[]>([]);
    const [categories, setCategories] = useState<string[]>([]);
    const [selectedItemKeys, setSelectedItemKeys] = useState<Set<string>>(new Set());
    const [query, setQuery] = useState('');
    const [searchQuery, setSearchQuery] = useState('');
    const [sortBy, setSortBy] = useState<SortByType>('timestamp');
    const [categoryFilter, setCategoryFilter] = useState('all');
    const [isLoading, setIsLoading] = useState(false);
    const [isInitiallyLoading, setIsInitiallyLoading] = useState(true);
    const [result, setResult] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [systematicPrompts, setSystematicPrompts] = useState<string[]>([]);
    const [dynamicPrompts, setDynamicPrompts] = useState<string[]>([]);
    const [isBuilderModalOpen, setIsBuilderModalOpen] = useState(false);
    const [builderContext, setBuilderContext] = useState<string | null>(null);
    const [showScrollButton, setShowScrollButton] = useState(false);
    const [isSaveActionItemModalOpen, setIsSaveActionItemModalOpen] = useState(false);
    const [actionItemToSave, setActionItemToSave] = useState<Message | null>(null);

    const analysisResultRef = useRef<HTMLDivElement>(null);
    const analysisScrollRef = useRef<HTMLDivElement>(null);

    const loadData = useCallback(async () => {
      setIsInitiallyLoading(true);
      setError(null);
      try {
        const [backendCategories, backendItems] = await Promise.all([
          backend.fetchCategories(),
          backend.fetchVaultItems(),
        ]);
        
        setCategories(backendCategories);
        setAllItems(backendItems.map(item => ({ ...item, key: item.id })));
        setSelectedItemKeys(new Set(backendItems.map(item => item.id)));

      } catch (e) {
        console.error('Failed to load Vault from backend', e);
        setError("Could not connect to your Vault. Please try again later.");
      } finally {
        setIsInitiallyLoading(false);
      }
    }, []);
    
    useEffect(() => {
        loadData();
    }, [loadData]);

    useEffect(() => {
        const element = analysisScrollRef.current;
        if (element && isLoading) {
            const isScrolledToBottom = element.scrollHeight - element.scrollTop <= element.clientHeight + 50;
            if (isScrolledToBottom) {
                element.scrollTop = element.scrollHeight;
                setShowScrollButton(false);
            } else if (result) {
                setShowScrollButton(true);
            }
        }
    }, [result, isLoading]);

    const handleAnalysisScroll = () => {
        const element = analysisScrollRef.current;
        if (element) {
            const isAtBottom = element.scrollHeight - element.scrollTop <= element.clientHeight + 20;
            if (isAtBottom) {
                setShowScrollButton(false);
            }
        }
    };


    const enabledOrigins = useMemo(() => {
        const origins = new Set<string>(['smepro']);
        if (userProfile.apiConnectors) {
            for (const connector of userProfile.apiConnectors) {
                if (connector.isEnabled) {
                    origins.add(connector.provider);
                }
            }
        }
        return origins;
    }, [userProfile.apiConnectors]);
    
    const visibleItems = useMemo(() => {
        return allItems.filter(item => enabledOrigins.has(item.origin || 'smepro'));
    }, [allItems, enabledOrigins]);
    
    const generateSystematicPrompts = useCallback((selectedItems: VaultItem[]): string[] => {
        if (selectedItems.length === 0) return [];
        const prompts = new Set<string>();
        prompts.add("Summarize the key takeaways from the selected items.");
        prompts.add("Identify the core themes across this selection.");
        if (selectedItems.length > 2) prompts.add("Find any conflicting information in the selection.");
        prompts.add("Create an action plan based on these items.");
        return Array.from(prompts).slice(0, 4);
    }, []);


    useEffect(() => {
        const selected = visibleItems.filter(i => selectedItemKeys.has(i.key));
        const newPrompts = generateSystematicPrompts(selected);
        setSystematicPrompts(newPrompts);
    }, [selectedItemKeys, visibleItems, generateSystematicPrompts]);


    const searchedItems = useMemo(() => {
        if (!searchQuery.trim()) {
            return visibleItems;
        }
        const lowerCaseQuery = searchQuery.toLowerCase();
        return visibleItems.filter(item => {
            const contentMatch = item.message.parts.some(part => part.text?.toLowerCase().includes(lowerCaseQuery));
            const titleMatch = item.sessionTitle?.toLowerCase().includes(lowerCaseQuery);
            const smeMatch = 
                item.smeConfig.industry.toLowerCase().includes(lowerCaseQuery) ||
                item.smeConfig.subType.toLowerCase().includes(lowerCaseQuery) ||
                item.smeConfig.segment.toLowerCase().includes(lowerCaseQuery);
            
            return contentMatch || titleMatch || smeMatch;
        });
    }, [visibleItems, searchQuery]);

    const filteredItems = useMemo(() => {
      if (categoryFilter === 'all') {
        return searchedItems;
      }
      return searchedItems.filter(item => item.category === categoryFilter);
    }, [searchedItems, categoryFilter]);

    const sortedItems = useMemo(() => {
        return [...filteredItems].sort((a, b) => {
            if (sortBy === 'category') return (a.category || '').localeCompare(b.category || '');
            if (sortBy === 'context') {
                const contextA = `${a.smeConfig.industry}${a.smeConfig.subType}${a.smeConfig.segment}`;
                const contextB = `${b.smeConfig.industry}${b.smeConfig.subType}${b.smeConfig.segment}`;
                return contextA.localeCompare(contextB);
            }
            return b.savedAt - a.savedAt; // Default 'timestamp'
        });
    }, [filteredItems, sortBy]);
    
    const handleAnalysisClick = (e: React.MouseEvent<HTMLElement>) => {
        const target = e.target as HTMLElement;

        if (target.matches('[data-task-item]')) {
            const taskText = target.getAttribute('data-task-item');
            if (taskText) {
                setActionItemToSave({ role: 'model', parts: [{ text: taskText }] });
                setIsSaveActionItemModalOpen(true);
                return;
            }
        }
        
        if (target.tagName === 'BUTTON' && target.classList.contains('actionable-bold')) {
            const text = target.textContent;
            if (text) {
                setBuilderContext(text);
                setIsBuilderModalOpen(true);
            }
        }
    };

    const handleToggleItem = (key: string) => {
        const newSelection = new Set(selectedItemKeys);
        newSelection.has(key) ? newSelection.delete(key) : newSelection.add(key);
        setSelectedItemKeys(newSelection);
    };

    const handleSelectAll = (select: boolean) => {
        setSelectedItemKeys(select ? new Set(filteredItems.map(i => i.key)) : new Set());
    };

    const handleAnalyze = async (analysisQuery: string) => {
        if (!analysisQuery.trim()) return;
        const selectedItemsForAnalysis = visibleItems.filter(i => selectedItemKeys.has(i.key));
        if (selectedItemsForAnalysis.length === 0) {
            setResult("Please select one or more items from your Vault to analyze.");
            return;
        }

        setIsLoading(true);
        setResult('');
        setError(null);
        setDynamicPrompts([]);

        try {
            if (!process.env.API_KEY) throw new Error("API_KEY not set.");
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
            const contextForAnalysis = selectedItemsForAnalysis.map(item => `--- VAULT ITEM START ---\nContent:\n${item.message.parts.map(p => p.text || '[Non-text content]').join('\n')}\n--- VAULT ITEM END ---`).join('\n\n');
            const systemInstruction = { text: `Analyze the user's curated knowledge from their Vault based on their query ("${analysisQuery}"). Synthesize connections and insights. Key actionable insights MUST be wrapped in **bold markdown**. Action items should be formatted as a markdown task list (e.g., "- [ ] Do this."). After your analysis, add a final line: \`DYNAMIC_PROMPTS: ["prompt1", "prompt2"]\`.` };

            const responseStream = await ai.models.generateContentStream({
                model: 'gemini-2.5-pro',
                contents: [{ role: 'user', parts: [systemInstruction, { text: contextForAnalysis }] }],
            });
            
            let fullResponseText = '';
            for await (const chunk of responseStream) {
                fullResponseText += chunk.text;
                const promptMarker = 'DYNAMIC_PROMPTS:';
                const promptIndex = fullResponseText.indexOf(promptMarker);
                const visibleText = promptIndex > -1 ? fullResponseText.substring(0, promptIndex) : fullResponseText;
                setResult(visibleText);
            }

            const promptMarker = 'DYNAMIC_PROMPTS:';
            const promptIndex = fullResponseText.indexOf(promptMarker);
            if (promptIndex > -1) {
              const promptJson = fullResponseText.substring(promptIndex + promptMarker.length);
              try { setDynamicPrompts(JSON.parse(promptJson)); } catch (e) { console.error("Failed to parse dynamic prompts", e); }
            }
        } catch (e) {
            const errorMessage = e instanceof Error ? e.message : "An unknown error occurred.";
            setError(`Analysis failed: ${errorMessage}`);
        } finally {
            setIsLoading(false);
        }
    };
    
    const handleFormSubmit = (e: React.FormEvent) => { e.preventDefault(); handleAnalyze(query); };
    const handleSystematicPromptClick = (prompt: string) => { setQuery(prompt); setTimeout(() => handleAnalyze(prompt), 0); };
    const handleSaveFromBuilder = async (content: string, title: string) => {
        const newItem: VaultItem = { id: `vault_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`, smeConfig: { industry: 'SMEPro Builder', subType: 'Generated Content', segment: title }, message: { role: 'model', parts: [{ text: content }] }, savedAt: Date.now(), category: 'Strategic Plans', syncStatus: 'pending', sessionTitle: 'Generated from Vault Analysis', origin: 'smepro' };
        try {
            await backend.saveVaultItem(newItem);
            const syncedItem: ExtendedVaultItem = { ...newItem, syncStatus: 'synced', key: newItem.id };
            setAllItems(prev => [...prev, syncedItem]);
            setSelectedItemKeys(prev => new Set(prev).add(syncedItem.key));
            setIsBuilderModalOpen(false);
            setBuilderContext(null);
        } catch (e) { setError("Failed to save the generated content to your Vault."); }
    };
    const getMessageSnippet = (item: VaultItem): React.ReactNode => {
        const text = item.message.parts.find(p => p.text)?.text || '';
        return text.substring(0, 100) + (text.length > 100 ? '...' : '');
    };
    
    const analysisMarked = useMemo(() => {
        const m = new Marked({ gfm: true, breaks: true });
        const renderer = new m.Renderer();
        
        // FIX: Update renderer signature to accept a token object as expected by the type definitions.
        // Use the `task` and `text` properties from the token instead of regex parsing.
        renderer.listitem = (item: { text: string; task?: boolean; checked?: boolean }) => {
            if (item.task) {
                const itemText = item.text;
                // Sanitize text for data attribute
                const sanitizedText = itemText.replace(/"/g, '&quot;').replace(/\n/g, ' ');
                return `<li class="task-list-item"><button data-task-item="${sanitizedText}" class="task-checkbox"></button><div class="task-text">${m.parseInline(itemText)}</div></li>`;
            }
            return `<li>${m.parseInline(item.text)}</li>`;
        };
        m.use({ renderer });
        return m;
    }, []);

    const renderResult = () => {
        if (isLoading && !result) return <div className="flex items-center justify-center h-full"><div className="text-center text-slate-400"><div className="w-10 h-10 border-4 border-t-cyan-500 border-slate-600 rounded-full animate-spin mx-auto mb-4"></div><p>Analyzing...</p></div></div>;
        if (!query && !isLoading) return <div className="flex items-center justify-center h-full"><div className="text-center text-slate-500 max-w-sm"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-16 h-16 mx-auto mb-4"><path d="M5.625 1.5c-1.036 0-1.875.84-1.875 1.875v17.25c0 1.035.84 1.875 1.875 1.875h12.75c1.035 0 1.875-.84 1.875-1.875V12.75A3.75 3.75 0 0 0 16.5 9h-1.875a.375.375 0 0 1-.375-.375V6.75A3.75 3.75 0 0 0 10.5 3H5.625Z" /><path d="M12.971 1.816A5.23 5.23 0 0 1 15.75 3v3.75a2.25 2.25 0 0 1-2.25 2.25h-1.5a.75.75 0 0 1-.75-.75V3a.75.75 0 0 1 .75-.75h1.5c.355 0 .694.085.99.233.15.076.312.14.471.192Z" /></svg><h3 className="text-xl font-bold text-slate-300">SMEPro Vault</h3><p className="mt-2 text-sm">Select saved insights, ask a question, and the SME will synthesize new knowledge for you.</p></div></div>;
        
        const rawHtml = analysisMarked.parse(result) as string;
        let finalHtml = rawHtml.replace(/<strong>(.*?)<\/strong>/g, `<button class="actionable-bold text-cyan-400 font-bold hover:underline focus:outline-none focus:ring-2 focus:ring-cyan-500 rounded px-1 -mx-1">$1</button>`);

        if (isLoading && result) {
            finalHtml += '<span class="blinking-cursor ml-1">|</span>';
        }
        return <div ref={analysisResultRef} onClick={handleAnalysisClick} className="prose prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: finalHtml }} />;
    };

    return (
      <>
        <div className="context-search-container flex h-full bg-slate-800">
            <div className="w-1/3 min-w-[300px] max-w-[400px] flex flex-col bg-slate-900/50 border-r border-slate-700 p-3">
                <header className="flex-shrink-0 mb-3">
                    <div className="flex justify-between items-center"><h2 className="text-lg font-bold text-white">SMEPro Vault</h2><button onClick={onClose} className="p-1 rounded-full text-slate-400 hover:bg-slate-700" aria-label="Close Vault"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5"><path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z" /></svg></button></div>
                    <div className="relative mt-3">
                        <input
                            type="search"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder="Search vault..."
                            className="w-full p-2 pl-8 bg-slate-700 border border-slate-600 rounded-lg text-sm text-white placeholder:text-slate-500 focus:ring-2 focus:ring-cyan-500 outline-none"
                        />
                        <svg className="absolute left-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M9 3.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11ZM2 9a7 7 0 1 1 12.452 4.391l3.328 3.329a.75.75 0 1 1-1.06 1.06l-3.329-3.328A7 7 0 0 1 2 9Z" clipRule="evenodd" /></svg>
                    </div>
                    <div className="grid grid-cols-2 gap-2 mt-2 text-sm"><div className="flex items-center gap-2"><span className="text-slate-400">Sort:</span><select value={sortBy} onChange={(e) => setSortBy(e.target.value as SortByType)} className="bg-slate-700 border-slate-600 rounded-md px-2 py-0.5 text-xs text-white w-full"><option value="timestamp">Date</option><option value="context">SME</option><option value="category">Category</option></select></div><div className="flex items-center gap-2"><span className="text-slate-400">Filter:</span><select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} className="bg-slate-700 border-slate-600 rounded-md px-2 py-0.5 text-xs text-white w-full"><option value="all">All</option>{categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}</select></div></div>
                    <div className="flex items-center justify-between mt-2 text-sm"><button onClick={onManageCategories} className="text-cyan-500 hover:underline text-xs">Manage Categories</button><div className="flex gap-2"><button onClick={() => handleSelectAll(true)} className="text-cyan-500 hover:underline text-xs">All</button><button onClick={() => handleSelectAll(false)} className="text-cyan-500 hover:underline text-xs">None</button></div></div>
                </header>
                <div className="flex-grow overflow-y-auto space-y-2 pr-1 -mr-2 min-h-0">
                    {isInitiallyLoading ? <p className="text-center text-slate-500 text-sm p-4">Connecting to Vault...</p> : sortedItems.length > 0 ? (sortedItems.map(item => {
                        const isBuilderItem = item.smeConfig.industry === 'SMEPro Builder';
                        return (
                        <div key={item.key} onClick={() => handleToggleItem(item.key)} className={`p-2.5 rounded-lg cursor-pointer border ${selectedItemKeys.has(item.key) ? 'bg-cyan-900/50 border-cyan-700' : 'bg-slate-800 hover:bg-slate-700/50 border-slate-700'}`}>
                            <div className="flex items-start gap-2.5">
                                <input type="checkbox" checked={selectedItemKeys.has(item.key)} readOnly className="mt-1 h-4 w-4 rounded border-slate-500 bg-slate-700 text-cyan-600"/>
                                <div className="flex-grow overflow-hidden flex items-start gap-2">
                                    {isBuilderItem && <BuilderIcon />}
                                    <div className="flex-grow overflow-hidden">
                                        <p className="font-semibold text-white text-sm truncate" title={isBuilderItem ? item.smeConfig.segment : item.sessionTitle || ''}>
                                            {isBuilderItem ? item.smeConfig.segment : (item.sessionTitle || getMessageSnippet(item))}
                                        </p>
                                        <p className="text-xs text-slate-400 truncate">{item.category}</p>
                                        <div className="flex items-center justify-between text-xs text-slate-500 mt-1">
                                            <div className="flex items-center gap-1.5">{item.origin && item.origin !== 'smepro' && <span title={`From ${item.origin}`} className="font-bold text-cyan-500">{item.origin.charAt(0).toUpperCase()}</span>}<span>{new Date(item.savedAt).toLocaleString()}</span></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )})) : (<p className="text-center text-slate-500 text-sm p-4">Your Vault is empty. Save insights or sync data from your API connectors.</p>)}
                </div>
            </div>
            <div className="flex-1 flex flex-col p-4 min-h-0">
                <div className="flex-grow flex flex-col bg-slate-700/30 rounded-lg relative min-h-0">
                    <div ref={analysisScrollRef} onScroll={handleAnalysisScroll} className={`flex-grow overflow-y-auto p-4 ${query ? '' : 'flex'}`}>
                        {renderResult()}
                    </div>
                    {showScrollButton && (
                        <button
                            onClick={() => {
                                analysisScrollRef.current?.scrollTo({ top: analysisScrollRef.current.scrollHeight, behavior: 'smooth' });
                            }}
                            className="absolute bottom-24 right-6 z-10 bg-cyan-600/80 text-white p-2 rounded-full shadow-lg hover:bg-cyan-500 backdrop-blur-sm transition-opacity animate-fade-in"
                            aria-label="Scroll to bottom"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5">
                                <path fillRule="evenodd" d="M10 3a.75.75 0 0 1 .75.75v10.69l3.22-3.22a.75.75 0 1 1 1.06 1.06l-4.5 4.5a.75.75 0 0 1-1.06 0l-4.5-4.5a.75.75 0 1 1 1.06-1.06l3.22 3.22V3.75A.75.75 0 0 1 10 3z" clipRule="evenodd" />
                            </svg>
                        </button>
                    )}
                    <div className="flex-shrink-0 p-3 border-t border-slate-700">
                        <form onSubmit={handleFormSubmit} className="flex items-center gap-2">
                            <input type="text" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Analyze curated knowledge..." className="w-full p-2 bg-slate-700 rounded-lg text-white" disabled={isLoading || isInitiallyLoading}/>
                            <button type="submit" disabled={isLoading || isInitiallyLoading || !query.trim() || selectedItemKeys.size === 0} className="bg-cyan-600 hover:bg-cyan-500 text-white font-bold py-2 px-4 rounded-lg disabled:bg-slate-600">Analyze</button>
                        </form>
                        <div className="mt-2">
                            <h4 className="text-xs font-semibold text-slate-400 mb-1">{result ? 'Next Step Prompts' : 'Systematic Prompts'}</h4>
                            <div className="flex flex-wrap gap-2">
                                {(result ? dynamicPrompts : systematicPrompts).map((prompt, i) => (<button key={i} onClick={() => handleSystematicPromptClick(prompt)} className="text-xs bg-slate-600 hover:bg-slate-500 text-slate-200 px-2 py-1 rounded-md" disabled={isLoading || isInitiallyLoading || selectedItemKeys.size === 0}>{prompt}</button>))}
                            </div>
                        </div>
                        {error && <p className="text-red-400 text-xs mt-2">{error}</p>}
                    </div>
                </div>
            </div>
        </div>
        {isBuilderModalOpen && builderContext && <SmeProBuilderModal context={builderContext} onClose={() => setIsBuilderModalOpen(false)} onSaveToVault={handleSaveFromBuilder} />}
        {isSaveActionItemModalOpen && actionItemToSave && (
            <SaveToVaultModal
                messageToSave={actionItemToSave}
                smeConfig={{ industry: 'Vault Analysis', subType: 'Action Item', segment: 'Generated Task' }}
                onClose={() => setIsSaveActionItemModalOpen(false)}
                onSuccess={() => { setIsSaveActionItemModalOpen(false); loadData(); }} // Reload data to show new item
                sessionTitle="From Vault Analysis"
                defaultCategory="Action Items"
            />
        )}
      </>
    );
};

export default Vault;